name 'chef_docker_wrapper'
maintainer 'Steve Brown'
maintainer_email 'sbrown@chef.io'
license 'Apache-2.0'
description 'Installs/Configures chef_docker_wrapper'
version '0.1.0'
chef_version '>= 14.0'
depends 'docker'
supports 'centos'

issues_url 'https://github.com/srb3/chef_docker_wrapper/issues'
source_url 'https://github.com/srb3/chef_docker_wrapper'
